### ISSUE TITLE
testFile

### ISSUE THREAD

**Issue by Pascal66** [fluzwup/Cryptonomicon#1]
Hello,
I've successfully compiled both flint and cryptonomicon. (on Android)
In order to do test on the last, I need  to have an example file to test all functions (as you do in flint with "MyRSATest")

**Comment by fluzwup** [comment]
I will put together a document with a bunch of operations that will test the various features.  I've got a version of the tool I use at work that runs against a hardware security module (HSM) which has been better tested; I'll use it to generate the data.  The format of the commands and output may differ slightly (the open source, all-software version lags a bit behind the HSM version), but the numbers should all match.  I should have that ready for you soon.

**Comment by Pascal66** [comment]
Perfect, I used your values to check my implementation, and get the same results.
(Some tests are missing I think like ARPC m2,  udk, skd)

**Comment by fluzwup** [comment]
The UDK and SKD functions are used internally by the Generate AC call.  The Visa CVN 10 version just uses the UDK to derive the card's secret key from the master key, using the PAN and sequence, and all the other methods used both UDK and SKD to generate a single-use session key; M/Chip uses the ATC and unpredictable number for the session key derivation, while Visa CVN 
[cryptonomicon.1.zip](https://github.com/fluzwup/Cryptonomicon/files/3744287/cryptonomicon.1.zip)
18 and EMV CVN 5 use just the ATC.  You can run the udk and skd commands, and compare the output to the keys generated by the generateAC command to ensure the I/O is working right.

As for ARPC method 2, I have a man page for the HSM version I wrote for work that I will eventually move over that has an example.  I've got a few functions in the HSM version that aren't in the open-source version yet, so the man page won't work fully (for example, in the HSM version the keys are referenced by name rather than by value), but it has a section of examples that has more context than what I put in the test file.

I'm attaching the nroff file for the man page (view with "man -l cryptonomicon.1" on a Linux system) and a text file of the formatted output.  You should be able to test with the example from that file.  I couldn't remember yesterday what case it was used for, it looks like it's for Visa CVN 18, and it truncates the ARPC down to 4 bytes.  I think a 4 byte card status update bitfield is appended to that in the clear when it's sent to the card, but I'd have to go check to see.

[cryptonomicon.1.zip](https://github.com/fluzwup/Cryptonomicon/files/3744295/cryptonomicon.1.zip)
[man_page_output.txt](https://github.com/fluzwup/Cryptonomicon/files/3744309/man_page_output.txt)

**Comment by Pascal66** [comment]
I'll read the man page. Thank you.
